{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "spree-app1.serviceAccountName" . }}
  labels:
{{ include "spree-app1.labels" . | indent 4 }}
{{- end -}}
